### ISSUE TITLE
Pronouns in general don't load

### ISSUE THREAD

**Issue by Froozigiusz** [frigid14/frigid-old#92]
Flavour text of a zombie lack the pronouns, but I don't know if the used pronouns should be of a deceased person or an "it".

_If_ the correct pronound should be "it", then additionally in my opinion the "human" part of the description shoud be changed to a gender. This way we could identify the walking corpse somewhat better.

![Zrzut ekranu z 2022-10-22 14-52-52](https://user-images.githubusercontent.com/77325322/197341000-1642f247-2ae3-478a-899d-b15efd92df25.png)

**Comment by Froozigiusz** [comment]
Just had a round, saw that player itself also doesn't have working pronouns

**Comment by Just-a-Unity-Dev** [comment]
#96 should fix this

**Comment by Just-a-Unity-Dev** [comment]
misclick

**Comment by Froozigiusz** [comment]
#96 didn't fix it for me


![Zrzut ekranu z 2022-10-23 16-07-22](https://user-images.githubusercontent.com/77325322/197396822-885f6222-1f50-48ef-87d6-cd40559faf67.png)
need to re-open this issue
